spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_caso_autoservicio
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    cors:
      allow-credentials: true
      allowed-origins:
        - http://localhost:4200
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      max-age: 3600